flags: {}
packages:
- '.'
- '../pontarius-xmpp/'
- '../reactive-banana/reactive-banana/'
extra-deps:
- stringprep-1.0.0

ghc-options:
  $everything: -dynamic -shared -fllvm -fPIC

resolver: nightly-2017-11-20
#resolver: lts-9.14
